logging:
  level:
    root: INFO

server:
  port: ${PORT:8080}

spring:
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      authentication-database: admin
      username: ${MONGODB_USERNAME:productListUser}
      password: ${MONGODB_PASSWORD:productListPassword}
      database: ${MONGODB_DATABASE:promotions}